// USER
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";

// CURRENT USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";

// FOLLOW
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const ADD_FOLLOWING = "ADD_FOLLOWING";
export const REMOVE_FOLLOWING = "REMOVE_FOLLOWING";
export const REMOVE_FOLLOWER = "REMOVE_FOLLOWER";

// POST
export const GET_POSTS = "GET_POSTS";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";

// FAVORITE
export const GET_FAVORITES = "GET_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

// COMMENT
export const GET_POST_COMMENTS = "GET_POST_COMMENTS";
export const GET_USER_COMMENTS = "GET_USER_COMMENTS";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

// AUTH
export const AUTH_ERROR = "AUTH_ERROR";

// MESSAGE
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// ERROR
export const GET_ERRORS = "GET_ERRORS";
