// USER
export const GET_USERS = "GET_USERS";

// CURRENT USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";

// FOLLOW
export const GET_USER_FOLLOWERS = "GET_USER_FOLLOWERS";
export const GET_USER_FOLLOWINGS = "GET_USER_FOLLOWINGS";
export const ADD_USER_FOLLOWING = "ADD_USER_FOLLOWING";
export const REMOVE_USER_FOLLOWING = "REMOVE_USER_FOLLOWING";
export const REMOVE_USER_FOLLOWER = "REMOVE_USER_FOLLOWER";

// POST
export const GET_POSTS = "GET_POSTS";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const CREATE_USER_POST = "CREATE_USER_POST";
export const DELETE_USER_POST = "DELETE_USER_POST";

// FAVORITE
export const ADD_USER_FAVORITES = "ADD_USER_FAVORITES";
export const REMOVE_USER_FAVORITE = "REMOVE_USER_FAVORITE";

// COMMENT
export const GET_POST_COMMENTS = "GET_POST_COMMENTS";
export const GET_USER_COMMENTS = "GET_USER_COMMENTS";

export const CREATE_USER_COMMENT = "CREATE_USER_COMMENT";
export const DELETE_USER_COMMENT = "DELETE_USER_COMMENT";
